# Generated by Django 4.1.7 on 2023-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bar_has_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='has_cover',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Cover Charge'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='bev_name',
            field=models.CharField(max_length=50, verbose_name='Libation'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='is_alcohol',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Contains Alcohol'),
        ),
    ]
