# Generated by Django 4.2 on 2023-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_bar_site_traffic_alter_beverage_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['-site_traffic']},
        ),
    ]
